name: Checkout and cache

on:
  workflow_call:
    inputs:
      repository:
        description: Repository name with owner (e.g. actions/checkout)
        type: string
        default: ${{ github.repository }}

      ref:
        description: Name of the ref to get (e.g. refs/heads/main)
        type: string
        default: ${{ github.ref }}

      path:
        description: Relative path under $GITHUB_WORKSPACE to place the repository
        type: string
        default: ./

      lfs:
        description: Whether to fetch Git LFS files
        type: boolean
        default: false

    secrets:
      changelog_token:
        description: GitHub token with elevated privileges

    outputs:
      github_sha:
        description: GitHub SHA
        value: ${{ jobs.checkout.outputs.github_sha }}

      github_sha_short:
        description: First 8 characters of GitHub SHA
        value: ${{ jobs.checkout.outputs.github_sha_short }}

      cache_key:
        description: Cache key
        value: ${{ jobs.checkout.outputs.cache_key }}

      cache_path:
        description: Cache path
        value: ${{ jobs.checkout.outputs.cache_path }}

jobs:
  github-ref:
    uses: ./.github/workflows/github-ref-v1.yml
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}
    secrets: inherit

  checkout:
    needs: github-ref

    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        id: vars
        run: |
          # We use the git SHA in the cache key, but checking out the repository
          # to get the SHA would defeat the purpose of the cache. We work around
          # this checken/egg by getting the SHA via the GitHub API instead.
          echo "cache_key=${{ inputs.repository }}/${{ needs.github-ref.outputs.github_sha_short }}" >> $GITHUB_OUTPUT
          echo "cache_path=${{ inputs.path }}" >> $GITHUB_OUTPUT

      - name: Cache checkout
        id: cache
        uses: actions/cache@v4
        with:
          key: ${{ steps.vars.outputs.cache_key }}
          path: ${{ steps.vars.outputs.cache_path }}

      - name: Checkout
        uses: actions/checkout@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          path: ${{ steps.vars.outputs.cache_path }}
          token: ${{ secrets.CHANGELOG_TOKEN || secrets.GITHUB_TOKEN }}
          lfs: ${{ inputs.lfs }}

    outputs:
      github_sha: ${{ needs.github-ref.outputs.github_sha_short }}
      github_sha_short: ${{ needs.github-ref.outputs.github_sha_short }}
      cache_key: ${{ steps.vars.outputs.cache_key }}
      cache_path: ${{ steps.vars.outputs.cache_path }}
