name: Get a git reference from GitHub

on:
  workflow_call:
    inputs:
      repository:
        description: Repository name with owner (e.g. actions/checkout)
        type: string
        default: ${{ github.repository }}

      ref:
        description: Name of the ref to get (e.g. [refs/]heads/main)
        type: string
        default: ${{ github.ref }}

    secrets:
      changelog_token:
        description: GitHub token with elevated privileges

    outputs:
      github_sha:
        description: Git SHA
        value: ${{ jobs.github-ref.outputs.github_sha }}

      github_sha_short:
        description: First 8 characters of Git SHA
        value: ${{ jobs.github-ref.outputs.github_sha_short }}

jobs:
  github-ref:
    runs-on: ubuntu-latest

    steps:
      - name: Modify ref for API
        id: api_ref
        run: echo "ref=$(echo ${{ inputs.ref }} | sed 's/^refs\///')" >> $GITHUB_OUTPUT

      - name: Get ref
        uses: octokit/request-action@v2.x
        id: ref
        with:
          route: GET /repos/${{ inputs.repository }}/git/ref/${{ steps.api_ref.outputs.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGELOG_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Set variables
        id: vars
        run: |
          github_sha=${{ fromJson(steps.ref.outputs.data).object.sha }}
          echo "::debug::Resolved '${{ inputs.ref }}' to '$github_sha' on '${{ inputs.repository }}'"
          echo "github_sha=$github_sha" >> $GITHUB_OUTPUT
          github_sha_short=${github_sha:0:8}
          echo "github_sha_short=$github_sha_short" >> $GITHUB_OUTPUT

    outputs:
      github_sha: ${{ steps.vars.outputs.github_sha }}
      github_sha_short: ${{ steps.vars.outputs.github_sha_short }}
